### ISSUE TITLE
synspec returns all nans

### ISSUE THREAD

**Issue by iancrossfield** [jobovy/apogee#52]
Following the examples for synspec yields only nans:
(I have to  Use an alternative linelist, since defaults aren't available online):
``atm= atlas9.Atlas9Atmosphere(teff=4750.,logg=2.5,metals=-0.25)
mylinelist = '/dash/exobox/proj/atmo/linelists/apogee/turbo_molec.DR12'
synspec= apogee.modelspec.turbospec.synth([26,-0.25,0.25],[22,-0.3],modelatm=atm, linelist=mylinelist, wmin=15000, wmax=15500, dw=0.2)
''
But the resulting synspec contains only nans.

**Comment by jobovy** [comment]
I don't think this is an actual example from the documentation, so I'm not sure I can help with figuring this out. Also, the ``'201404080919'`` linelist is available online (I believe the code will just download it automatically or you might have to do ``apogee.tools.download.linelist('201404080919')``, so please test first that the actual example from the documentation works. It may be that the parameters you changed are to blame for the error.

Also note that I am far from being a Turbospectrum expert and it has been a few years since I've used this code, so my ability to help with this might be very limited.
