### ISSUE TITLE
Selection function code dr14

### ISSUE THREAD

**Issue by wylie22s** [jobovy/apogee#54]
Hi 
Id like to use the selection function code with Dr14. I set  APOGEE_REDUX in my bashrc folder to l31c.2, and ran the command:

apo = apogee.select.apogeeSelect()

but I get the error:

IOError: No default year available for APOGEE_REDUX l31c.2, need to set it by hand

How do I set it by hand?
Thanks!

**Comment by jobovy** [comment]
The DR14 selection function code is not yet available (@jmackereth is working on it!), so for now you can only use the DR12 version. For that, you could set the year explicitly by specifying ``year=3`` in the ``apogeeSelect`` call, but note that using DR14 data with the DR12 selection function will likely lead to other issues due to the DR inconsistency.

**Comment by jobovy** [comment]
The DR14 and DR16 selection functions are now (as of 4e2a3e4) in the code.
